name: Docs

on:
  push:
    branches:
    - master
    paths:
    - docs/**
    - mkdocs.yml
    - .github/workflows/mkdocs-deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs==1.6.0
    - name: Build
      run: mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site