name: Docs

on:
  push:
    branches:
    - main
    paths:
    - docs/**
    - mkdocs.yml
    - .github/workflows/mkdocs-deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install mkdocs==1.6.0
    - run: mkdocs gh-deploy